const width = 20;
const height = 40;
const area = width * height;
console.log('value of area ' + area);
console.log('typeof area ' + typeof area);
const bill = 1000;
const payment = 5000;
const change = payment - bill;
console.log('value of change ' + change);
console.log('typeof change ' + typeof change);
const quizzes = 15;
const midterm = 54;
const final = 99;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade ' + grade);
console.log('typeof grade ' + typeof grade);
const firstName = 'Kitlong';
const lastName = 'Lai';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName ' + fullName);
console.log('typeof fullName ' + typeof fullName);
const pH = 14;
const isAcidic = pH < 7;
console.log('value of isAcidic ' + isAcidic);
console.log('typeof isAcidic ' + typeof isAcidic);
const headCount = 1500;
const isSparta = (headCount === 300);
console.log('value of isSparta ' + isSparta);
console.log('typeof isSparta ' + typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('value of motto ' + motto);
console.log('typeof motto ' + typeof motto);
